// Command seedtest populates a data directory with fake networks, buffers,
// and messages so the web UI can be exercised without a live IRC connection.
// It also writes <data-dir>/config.yaml naming the seeded networks: config
// is the boot source of truth, so without it the backend would mark every
// seeded network disabled on startup. The config points at unreachable
// loopback endpoints so nothing real is ever dialed.
//
// Usage:
//
//	go run ./cmd/seedtest --data-dir ./data-test [--reset]
//
// Then run the backend against the same directory:
//
//	DATA_DIR=./data-test CONFIG_PATH=./data-test/config.yaml go run . --web-dir ./web/dist
package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/uuid"
	ircdb "github.com/lepinkainen/lurker/db"
)

type seedNetwork struct {
	Name     string
	Host     string
	Port     int
	TLS      bool
	Nick     string
	Realname string
	Channels []seedChannel
	Queries  []seedQuery
}

type seedChannel struct {
	Name     string
	Topic    string
	Members  []string
	Archived bool
	Lines    []seedLine
}

type seedQuery struct {
	Nick     string
	Archived bool
	Lines    []seedLine
}

type seedLine struct {
	Sender  string
	Kind    string
	Content string
	Offset  time.Duration
}

// seedBufferRef identifies a seeded buffer by network and buffer name so
// fixtures can refer to buffers before their global IDs are known.
type seedBufferRef struct {
	Network string
	Buffer  string
}

func main() {
	dataDir := flag.String("data-dir", "./data-test", "data directory to seed")
	reset := flag.Bool("reset", false, "remove the data directory before seeding")
	flag.Parse()

	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stdout, nil)))

	if *reset {
		if err := os.RemoveAll(*dataDir); err != nil {
			slog.Error("reset data dir", "err", err)
			os.Exit(1)
		}
	}
	if err := os.MkdirAll(*dataDir, 0o755); err != nil {
		slog.Error("mkdir data dir", "err", err)
		os.Exit(1)
	}

	stores, err := ircdb.OpenMultiStore(*dataDir)
	if err != nil {
		slog.Error("open stores", "err", err)
		os.Exit(1)
	}
	defer func() { _ = stores.Close() }()

	ctx := context.Background()
	if err := seed(ctx, stores, fixture()); err != nil {
		slog.Error("seed", "err", err)
		os.Exit(1)
	}
	if err := writeConfigYAML(*dataDir, fixture()); err != nil {
		slog.Error("write config.yaml", "err", err)
		os.Exit(1)
	}
	slog.Info("seed complete", "data_dir", *dataDir)
}

// writeConfigYAML emits a config.yaml declaring the seeded networks so boot
// reconciliation keeps them enabled. Servers point at 127.0.0.1:1 (nothing
// listens there) so connect attempts fail instantly instead of reaching real
// IRC networks.
func writeConfigYAML(dataDir string, networks []seedNetwork) error {
	var b strings.Builder
	b.WriteString("# Generated by cmd/seedtest — pairs with the seeded data in this directory.\n")
	b.WriteString("networks:\n")
	for _, n := range networks {
		fmt.Fprintf(&b, "  - network: %s\n", n.Name)
		fmt.Fprintf(&b, "    nick: %s\n", n.Nick)
		fmt.Fprintf(&b, "    realname: %q\n", n.Realname)
		b.WriteString("    servers:\n")
		b.WriteString("      - host: 127.0.0.1\n")
		b.WriteString("        port: 1\n")
		b.WriteString("        tls: false\n")
	}
	return os.WriteFile(filepath.Join(dataDir, "config.yaml"), []byte(b.String()), 0o600)
}

func seed(ctx context.Context, stores *ircdb.MultiStore, networks []seedNetwork) error {
	base := time.Now().Add(-6 * time.Hour)
	channelIDs := map[seedBufferRef]uuid.UUID{}
	for _, n := range networks {
		net, err := stores.UpsertNetwork(ctx, ircdb.Network{
			Name: n.Name, Host: n.Host, Port: n.Port, TLS: n.TLS,
			Nick: n.Nick, Realname: n.Realname,
		})
		if err != nil {
			return fmt.Errorf("upsert network %q: %w", n.Name, err)
		}
		logStore, err := stores.LogStore(net.ID)
		if err != nil {
			return err
		}

		if _, err := ircdb.EnsureStatusBuffer(ctx, stores, net.ID); err != nil {
			return fmt.Errorf("status buffer %s: %w", n.Name, err)
		}
		if err := seedStatus(ctx, stores, logStore, net.ID, base); err != nil {
			return err
		}

		for _, c := range n.Channels {
			id, err := seedChannelBuffer(ctx, stores, logStore, net.ID, c, base)
			if err != nil {
				return fmt.Errorf("seed channel %s/%s: %w", n.Name, c.Name, err)
			}
			channelIDs[seedBufferRef{Network: n.Name, Buffer: c.Name}] = id
		}
		for _, q := range n.Queries {
			if err := seedQueryBuffer(ctx, stores, logStore, net.ID, q, base); err != nil {
				return fmt.Errorf("seed query %s/%s: %w", n.Name, q.Nick, err)
			}
		}
	}
	return seedPinned(ctx, stores, channelIDs, pinnedFixture())
}

// seedPinned pins the fixture channels and normalizes their pin_order to
// 0..n-1 in the declared order. It deliberately goes through the same
// functions the REST API uses (UpdateBufferSettings for the pin flag,
// ReorderPinnedBuffers for the ordering) so seeded data cannot drift from the
// invariants real clients rely on.
func seedPinned(ctx context.Context, stores *ircdb.MultiStore, channelIDs map[seedBufferRef]uuid.UUID, refs []seedBufferRef) error {
	if len(refs) == 0 {
		return nil
	}
	pinned := true
	order := make([]uuid.UUID, 0, len(refs))
	for _, ref := range refs {
		id, ok := channelIDs[ref]
		if !ok {
			return fmt.Errorf("pin fixture: unknown channel %s/%s", ref.Network, ref.Buffer)
		}
		if _, err := ircdb.UpdateBufferSettings(ctx, stores.Control, id, ircdb.BufferSettingsPatch{Pinned: &pinned}); err != nil {
			return fmt.Errorf("pin %s/%s: %w", ref.Network, ref.Buffer, err)
		}
		order = append(order, id)
	}
	entries, err := ircdb.ReorderPinnedBuffers(ctx, stores.Control, order)
	if err != nil {
		return fmt.Errorf("reorder pinned buffers: %w", err)
	}
	for _, ref := range refs {
		slog.Info("pinned buffer", "network", ref.Network, "buffer", ref.Buffer, "pin_order", pinOrderOf(entries, channelIDs[ref]))
	}
	return nil
}

func pinOrderOf(entries []ircdb.BufferSortEntry, id uuid.UUID) int64 {
	for _, e := range entries {
		if e.ID == id {
			return e.SortOrder
		}
	}
	return -1
}

func seedStatus(ctx context.Context, stores *ircdb.MultiStore, log *ircdb.LogStore, networkID uuid.UUID, base time.Time) error {
	localID, err := resolveLocalBuffer(ctx, stores, log, networkID, "", ircdb.BufferStatus)
	if err != nil {
		return err
	}
	lines := []seedLine{
		{Sender: "*", Kind: "connecting", Content: "connecting to server", Offset: 0},
		{Sender: "*", Kind: "connected", Content: "connected", Offset: 2 * time.Second},
		{Sender: "*", Kind: "notice", Content: "*** Looking up your hostname...", Offset: 3 * time.Second},
		{Sender: "*", Kind: "notice", Content: "*** Welcome to the network", Offset: 4 * time.Second},
	}
	return insertLines(ctx, log, localID, lines, base)
}

// seedChannelBuffer seeds one channel and returns its global buffer ID so
// callers can apply cross-network settings (e.g. pinning) afterwards.
func seedChannelBuffer(ctx context.Context, stores *ircdb.MultiStore, log *ircdb.LogStore, networkID uuid.UUID, c seedChannel, base time.Time) (uuid.UUID, error) {
	localID, err := resolveLocalBuffer(ctx, stores, log, networkID, c.Name, ircdb.BufferChannel)
	if err != nil {
		return uuid.Nil, err
	}
	if c.Topic != "" {
		if err := ircdb.UpdateLogBufferTopicState(ctx, log.DB, c.Name, &c.Topic, nil, nil); err != nil {
			return uuid.Nil, err
		}
	}
	if err := setArchived(ctx, stores, localID, c.Archived); err != nil {
		return uuid.Nil, err
	}
	if err := insertLines(ctx, log, localID, c.Lines, base); err != nil {
		return uuid.Nil, err
	}
	return localID, nil
}

// setArchived flips the persisted archived flag so seeded sidebars exercise
// the per-network Archive fold.
func setArchived(ctx context.Context, stores *ircdb.MultiStore, bufferID uuid.UUID, archived bool) error {
	if !archived {
		return nil
	}
	_, err := ircdb.UpdateBufferSettings(ctx, stores.Control, bufferID, ircdb.BufferSettingsPatch{Archived: &archived})
	return err
}

func seedQueryBuffer(ctx context.Context, stores *ircdb.MultiStore, log *ircdb.LogStore, networkID uuid.UUID, q seedQuery, base time.Time) error {
	localID, err := resolveLocalBuffer(ctx, stores, log, networkID, q.Nick, ircdb.BufferQuery)
	if err != nil {
		return err
	}
	if err := setArchived(ctx, stores, localID, q.Archived); err != nil {
		return err
	}
	return insertLines(ctx, log, localID, q.Lines, base)
}

func resolveLocalBuffer(ctx context.Context, stores *ircdb.MultiStore, _ *ircdb.LogStore, networkID uuid.UUID, name, kind string) (uuid.UUID, error) {
	id, _, _, err := stores.EnsureBuffer(ctx, networkID, name, kind)
	return id, err
}

func insertLines(ctx context.Context, log *ircdb.LogStore, bufferID uuid.UUID, lines []seedLine, base time.Time) error {
	for i, l := range lines {
		ts := base.Add(l.Offset + time.Duration(i)*time.Millisecond)
		_, _, _, err := ircdb.InsertLogMessage(ctx, log.DB, ircdb.LogMessageInput{
			BufferID:  bufferID,
			Timestamp: ts,
			Sender:    l.Sender,
			Kind:      l.Kind,
			Content:   l.Content,
		})
		if err != nil {
			return err
		}
	}
	return nil
}

// pinnedFixture lists the channels the seeder pins, in the order they should
// appear in the Pinned section (pin_order 0, 1, 2). The order deliberately
// spans two networks and is neither alphabetical (#debian < #go-nuts <
// #lurker) nor seed order, so a client that ignores pin_order and falls back
// to name or insertion order is immediately visible.
func pinnedFixture() []seedBufferRef {
	return []seedBufferRef{
		{Network: "libera", Buffer: "#go-nuts"},
		{Network: "oftc", Buffer: "#debian"},
		{Network: "libera", Buffer: "#lurker"},
	}
}

func fixture() []seedNetwork {
	return []seedNetwork{
		{
			Name: "libera", Host: "irc.libera.chat", Port: 6697, TLS: true,
			Nick: "lurkertest", Realname: "Lurker Test",
			Channels: []seedChannel{
				{
					Name:  "#lurker",
					Topic: "Lurker dev channel — test fixtures loaded",
					// buildbot exercises IRCv3 bot rendering: fixture mode
					// flags any nick ending in "bot" as a bot.
					Members: []string{"alice", "bob", "carol", "buildbot", "lurkertest"},
					Lines: []seedLine{
						{Sender: "alice", Kind: "privmsg", Content: "morning folks", Offset: 1 * time.Hour},
						{Sender: "bob", Kind: "privmsg", Content: "hey alice", Offset: 1*time.Hour + 30*time.Second},
						{Sender: "carol", Kind: "action", Content: "waves", Offset: 1*time.Hour + 2*time.Minute},
						{Sender: "alice", Kind: "privmsg", Content: "anyone seen the latest PR?", Offset: 1*time.Hour + 5*time.Minute},
						{Sender: "bob", Kind: "privmsg", Content: "looking now", Offset: 1*time.Hour + 6*time.Minute},
						{Sender: "lurkertest", Kind: "privmsg", Content: "LGTM from me", Offset: 1*time.Hour + 10*time.Minute},
						{Sender: "carol", Kind: "privmsg", Content: "same, merging", Offset: 1*time.Hour + 12*time.Minute},
						{Sender: "buildbot", Kind: "privmsg", Content: "build #412 passed in 2m14s", Offset: 1*time.Hour + 13*time.Minute},
					},
				},
				{
					Name:    "#go-nuts",
					Topic:   "Go programming — https://go.dev",
					Members: []string{"gopher1", "gopher2", "lurkertest"},
					Lines: []seedLine{
						{Sender: "gopher1", Kind: "privmsg", Content: "anyone using generics for sql scanning yet?", Offset: 2 * time.Hour},
						{Sender: "gopher2", Kind: "privmsg", Content: "yeah, works great with sqlc", Offset: 2*time.Hour + 45*time.Second},
						{Sender: "gopher1", Kind: "privmsg", Content: "nice, will try it out", Offset: 2*time.Hour + 2*time.Minute},
					},
				},
				{
					Name:     "#retired",
					Topic:    "Old project channel, no longer active",
					Archived: true,
					Lines: []seedLine{
						{Sender: "oldtimer", Kind: "privmsg", Content: "this channel had a good run", Offset: 30 * time.Minute},
					},
				},
			},
			Queries: []seedQuery{
				{
					Nick: "alice",
					Lines: []seedLine{
						{Sender: "alice", Kind: "privmsg", Content: "got a minute?", Offset: 3 * time.Hour},
						{Sender: "lurkertest", Kind: "privmsg", Content: "sure, what's up", Offset: 3*time.Hour + 20*time.Second},
						{Sender: "alice", Kind: "privmsg", Content: "pair on that auth bug later?", Offset: 3*time.Hour + 1*time.Minute},
					},
				},
				{
					Nick:     "spammer",
					Archived: true,
					Lines: []seedLine{
						{Sender: "spammer", Kind: "privmsg", Content: "hot deals just for you!!!", Offset: 3 * time.Hour},
					},
				},
			},
		},
		{
			Name: "oftc", Host: "irc.oftc.net", Port: 6697, TLS: true,
			Nick: "lurkertest", Realname: "Lurker Test",
			Channels: []seedChannel{
				{
					Name:    "#debian",
					Topic:   "Debian user support",
					Members: []string{"deb1", "deb2", "lurkertest"},
					Lines: []seedLine{
						{Sender: "deb1", Kind: "privmsg", Content: "apt is hanging on trixie", Offset: 4 * time.Hour},
						{Sender: "deb2", Kind: "privmsg", Content: "try --fix-missing", Offset: 4*time.Hour + 30*time.Second},
					},
				},
			},
		},
	}
}
