version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
      include: scope
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      go-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      web-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
      include: scope
    groups:
      docker-minor:
        update-types:
          - minor
          - patch
