// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: buffer_registry.sql

package controldb

import (
	"context"
)

const deleteBufferRegistry = `-- name: DeleteBufferRegistry :exec
DELETE FROM buffer_registry WHERE id = ?
`

func (q *Queries) DeleteBufferRegistry(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, deleteBufferRegistry, id)
	return err
}

const insertBufferRegistry = `-- name: InsertBufferRegistry :exec
INSERT INTO buffer_registry(id, network_id, name, kind, created_at) VALUES (?, ?, ?, ?, ?)
`

type InsertBufferRegistryParams struct {
	ID        []byte
	NetworkID []byte
	Name      string
	Kind      string
	CreatedAt string
}

func (q *Queries) InsertBufferRegistry(ctx context.Context, arg InsertBufferRegistryParams) error {
	_, err := q.db.ExecContext(ctx, insertBufferRegistry,
		arg.ID,
		arg.NetworkID,
		arg.Name,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}

const listBufferRegistryForNetwork = `-- name: ListBufferRegistryForNetwork :many
SELECT id, name, kind, created_at, sort_order FROM buffer_registry WHERE network_id = ? ORDER BY id
`

type ListBufferRegistryForNetworkRow struct {
	ID        []byte
	Name      string
	Kind      string
	CreatedAt string
	SortOrder int64
}

func (q *Queries) ListBufferRegistryForNetwork(ctx context.Context, networkID []byte) ([]ListBufferRegistryForNetworkRow, error) {
	rows, err := q.db.QueryContext(ctx, listBufferRegistryForNetwork, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBufferRegistryForNetworkRow{}
	for rows.Next() {
		var i ListBufferRegistryForNetworkRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelBuffersForNetwork = `-- name: ListChannelBuffersForNetwork :many
SELECT id, sort_order FROM buffer_registry WHERE network_id = ? AND kind = 'channel' ORDER BY id
`

type ListChannelBuffersForNetworkRow struct {
	ID        []byte
	SortOrder int64
}

func (q *Queries) ListChannelBuffersForNetwork(ctx context.Context, networkID []byte) ([]ListChannelBuffersForNetworkRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelBuffersForNetwork, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelBuffersForNetworkRow{}
	for rows.Next() {
		var i ListChannelBuffersForNetworkRow
		if err := rows.Scan(&i.ID, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupBufferRegistry = `-- name: LookupBufferRegistry :one
SELECT network_id, name, kind FROM buffer_registry WHERE id = ?
`

type LookupBufferRegistryRow struct {
	NetworkID []byte
	Name      string
	Kind      string
}

func (q *Queries) LookupBufferRegistry(ctx context.Context, id []byte) (LookupBufferRegistryRow, error) {
	row := q.db.QueryRowContext(ctx, lookupBufferRegistry, id)
	var i LookupBufferRegistryRow
	err := row.Scan(&i.NetworkID, &i.Name, &i.Kind)
	return i, err
}

const lookupBufferRegistryByName = `-- name: LookupBufferRegistryByName :one
SELECT id, kind, created_at FROM buffer_registry WHERE network_id = ? AND name = ?
`

type LookupBufferRegistryByNameParams struct {
	NetworkID []byte
	Name      string
}

type LookupBufferRegistryByNameRow struct {
	ID        []byte
	Kind      string
	CreatedAt string
}

func (q *Queries) LookupBufferRegistryByName(ctx context.Context, arg LookupBufferRegistryByNameParams) (LookupBufferRegistryByNameRow, error) {
	row := q.db.QueryRowContext(ctx, lookupBufferRegistryByName, arg.NetworkID, arg.Name)
	var i LookupBufferRegistryByNameRow
	err := row.Scan(&i.ID, &i.Kind, &i.CreatedAt)
	return i, err
}

const setBufferSortOrder = `-- name: SetBufferSortOrder :exec
UPDATE buffer_registry SET sort_order = ? WHERE id = ?
`

type SetBufferSortOrderParams struct {
	SortOrder int64
	ID        []byte
}

func (q *Queries) SetBufferSortOrder(ctx context.Context, arg SetBufferSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, setBufferSortOrder, arg.SortOrder, arg.ID)
	return err
}
