// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: buffer_settings.sql

package controldb

import (
	"context"
)

const bufferRegistryExists = `-- name: BufferRegistryExists :one
SELECT COUNT(1) FROM buffer_registry WHERE id = ?
`

func (q *Queries) BufferRegistryExists(ctx context.Context, id []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, bufferRegistryExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBufferRegistryKind = `-- name: GetBufferRegistryKind :one
SELECT kind FROM buffer_registry WHERE id = ?
`

func (q *Queries) GetBufferRegistryKind(ctx context.Context, id []byte) (string, error) {
	row := q.db.QueryRowContext(ctx, getBufferRegistryKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const getBufferSettings = `-- name: GetBufferSettings :one
SELECT buffer_id, show_embeds, show_presence_events, collapse_presence_events, pinned, updated_at, archived
FROM buffer_settings WHERE buffer_id = ?
`

func (q *Queries) GetBufferSettings(ctx context.Context, bufferID []byte) (BufferSetting, error) {
	row := q.db.QueryRowContext(ctx, getBufferSettings, bufferID)
	var i BufferSetting
	err := row.Scan(
		&i.BufferID,
		&i.ShowEmbeds,
		&i.ShowPresenceEvents,
		&i.CollapsePresenceEvents,
		&i.Pinned,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const listBufferSettings = `-- name: ListBufferSettings :many
SELECT buffer_id, show_embeds, show_presence_events, collapse_presence_events, pinned, updated_at, archived
FROM buffer_settings
`

func (q *Queries) ListBufferSettings(ctx context.Context) ([]BufferSetting, error) {
	rows, err := q.db.QueryContext(ctx, listBufferSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BufferSetting{}
	for rows.Next() {
		var i BufferSetting
		if err := rows.Scan(
			&i.BufferID,
			&i.ShowEmbeds,
			&i.ShowPresenceEvents,
			&i.CollapsePresenceEvents,
			&i.Pinned,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBufferSettings = `-- name: UpsertBufferSettings :exec
INSERT INTO buffer_settings(buffer_id, show_embeds, show_presence_events, collapse_presence_events, pinned, updated_at, archived)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(buffer_id) DO UPDATE SET
  show_embeds=excluded.show_embeds,
  show_presence_events=excluded.show_presence_events,
  collapse_presence_events=excluded.collapse_presence_events,
  pinned=excluded.pinned,
  updated_at=excluded.updated_at,
  archived=excluded.archived
`

type UpsertBufferSettingsParams struct {
	BufferID               []byte
	ShowEmbeds             int64
	ShowPresenceEvents     int64
	CollapsePresenceEvents int64
	Pinned                 int64
	UpdatedAt              string
	Archived               int64
}

func (q *Queries) UpsertBufferSettings(ctx context.Context, arg UpsertBufferSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertBufferSettings,
		arg.BufferID,
		arg.ShowEmbeds,
		arg.ShowPresenceEvents,
		arg.CollapsePresenceEvents,
		arg.Pinned,
		arg.UpdatedAt,
		arg.Archived,
	)
	return err
}
