// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: highlights.sql

package controldb

import (
	"context"
)

const deleteAllHighlights = `-- name: DeleteAllHighlights :exec
DELETE FROM highlights
`

func (q *Queries) DeleteAllHighlights(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllHighlights)
	return err
}

const insertHighlight = `-- name: InsertHighlight :exec
INSERT OR IGNORE INTO highlights (id, pattern, created_at) VALUES (?, ?, ?)
`

type InsertHighlightParams struct {
	ID        []byte
	Pattern   string
	CreatedAt string
}

func (q *Queries) InsertHighlight(ctx context.Context, arg InsertHighlightParams) error {
	_, err := q.db.ExecContext(ctx, insertHighlight, arg.ID, arg.Pattern, arg.CreatedAt)
	return err
}

const listHighlights = `-- name: ListHighlights :many
SELECT pattern FROM highlights ORDER BY created_at
`

func (q *Queries) ListHighlights(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHighlights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var pattern string
		if err := rows.Scan(&pattern); err != nil {
			return nil, err
		}
		items = append(items, pattern)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
