// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ignores.sql

package controldb

import (
	"context"
)

const createIgnore = `-- name: CreateIgnore :exec
INSERT OR IGNORE INTO ignores (id, network_id, mask, created_at) VALUES (?, ?, ?, ?)
`

type CreateIgnoreParams struct {
	ID        []byte
	NetworkID []byte
	Mask      string
	CreatedAt string
}

func (q *Queries) CreateIgnore(ctx context.Context, arg CreateIgnoreParams) error {
	_, err := q.db.ExecContext(ctx, createIgnore,
		arg.ID,
		arg.NetworkID,
		arg.Mask,
		arg.CreatedAt,
	)
	return err
}

const deleteIgnore = `-- name: DeleteIgnore :exec
DELETE FROM ignores WHERE network_id = ? AND mask = ?
`

type DeleteIgnoreParams struct {
	NetworkID []byte
	Mask      string
}

func (q *Queries) DeleteIgnore(ctx context.Context, arg DeleteIgnoreParams) error {
	_, err := q.db.ExecContext(ctx, deleteIgnore, arg.NetworkID, arg.Mask)
	return err
}

const listIgnores = `-- name: ListIgnores :many
SELECT mask FROM ignores WHERE network_id = ? ORDER BY created_at
`

func (q *Queries) ListIgnores(ctx context.Context, networkID []byte) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listIgnores, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var mask string
		if err := rows.Scan(&mask); err != nil {
			return nil, err
		}
		items = append(items, mask)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
