// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package controldb

import (
	"database/sql"
)

type BufferRegistry struct {
	ID        []byte
	NetworkID []byte
	Name      string
	Kind      string
	CreatedAt string
}

type BufferSetting struct {
	BufferID               []byte
	ShowEmbeds             int64
	ShowPresenceEvents     int64
	CollapsePresenceEvents int64
	Pinned                 int64
	UpdatedAt              string
}

type Ignore struct {
	ID        []byte
	NetworkID []byte
	Mask      string
	CreatedAt string
}

type Network struct {
	ID          []byte
	Name        string
	NameCi      string
	Host        string
	Port        int64
	Tls         int64
	Nick        string
	Realname    sql.NullString
	SaslUser    sql.NullString
	SaslPass    sql.NullString
	Autoconnect int64
	CreatedAt   string
	SortOrder   int64
	Disabled    int64
	Kind        string
}

type NetworkConnectCommand struct {
	NetworkID []byte
	Position  int64
	Command   string
}
