// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: networks.sql

package controldb

import (
	"context"
	"database/sql"
)

const createNetwork = `-- name: CreateNetwork :exec
INSERT INTO networks(id, name, name_ci, kind, host, port, tls, nick, realname, sasl_user, sasl_pass, autoconnect, sort_order, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1,
        (SELECT COALESCE(MAX(sort_order) + 1, 0) FROM networks), ?)
`

type CreateNetworkParams struct {
	ID        []byte
	Name      string
	NameCi    string
	Kind      string
	Host      string
	Port      int64
	Tls       int64
	Nick      string
	Realname  sql.NullString
	SaslUser  sql.NullString
	SaslPass  sql.NullString
	CreatedAt string
}

func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) error {
	_, err := q.db.ExecContext(ctx, createNetwork,
		arg.ID,
		arg.Name,
		arg.NameCi,
		arg.Kind,
		arg.Host,
		arg.Port,
		arg.Tls,
		arg.Nick,
		arg.Realname,
		arg.SaslUser,
		arg.SaslPass,
		arg.CreatedAt,
	)
	return err
}

const deleteNetwork = `-- name: DeleteNetwork :execrows
DELETE FROM networks WHERE id = ?
`

func (q *Queries) DeleteNetwork(ctx context.Context, id []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNetwork, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNetwork = `-- name: GetNetwork :one
SELECT id, name, kind, host, port, tls, nick, COALESCE(realname,'') AS realname,
       sasl_user, sasl_pass, sort_order, disabled
FROM networks WHERE id = ?
`

type GetNetworkRow struct {
	ID        []byte
	Name      string
	Kind      string
	Host      string
	Port      int64
	Tls       int64
	Nick      string
	Realname  string
	SaslUser  sql.NullString
	SaslPass  sql.NullString
	SortOrder int64
	Disabled  int64
}

func (q *Queries) GetNetwork(ctx context.Context, id []byte) (GetNetworkRow, error) {
	row := q.db.QueryRowContext(ctx, getNetwork, id)
	var i GetNetworkRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Host,
		&i.Port,
		&i.Tls,
		&i.Nick,
		&i.Realname,
		&i.SaslUser,
		&i.SaslPass,
		&i.SortOrder,
		&i.Disabled,
	)
	return i, err
}

const getNetworkIDByNameCI = `-- name: GetNetworkIDByNameCI :one
SELECT id FROM networks WHERE name_ci = ?
`

func (q *Queries) GetNetworkIDByNameCI(ctx context.Context, nameCi string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getNetworkIDByNameCI, nameCi)
	var id []byte
	err := row.Scan(&id)
	return id, err
}

const listNetworkIDs = `-- name: ListNetworkIDs :many
SELECT id FROM networks
`

func (q *Queries) ListNetworkIDs(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listNetworkIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var id []byte
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworks = `-- name: ListNetworks :many
SELECT id, name, kind, host, port, tls, nick, COALESCE(realname,'') AS realname, sort_order, disabled
FROM networks ORDER BY sort_order, id
`

type ListNetworksRow struct {
	ID        []byte
	Name      string
	Kind      string
	Host      string
	Port      int64
	Tls       int64
	Nick      string
	Realname  string
	SortOrder int64
	Disabled  int64
}

func (q *Queries) ListNetworks(ctx context.Context) ([]ListNetworksRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetworksRow{}
	for rows.Next() {
		var i ListNetworksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Host,
			&i.Port,
			&i.Tls,
			&i.Nick,
			&i.Realname,
			&i.SortOrder,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworksWithSASL = `-- name: ListNetworksWithSASL :many
SELECT id, name, kind, host, port, tls, nick, COALESCE(realname,'') AS realname,
       sasl_user, sasl_pass, sort_order
FROM networks WHERE disabled=0 ORDER BY sort_order, id
`

type ListNetworksWithSASLRow struct {
	ID        []byte
	Name      string
	Kind      string
	Host      string
	Port      int64
	Tls       int64
	Nick      string
	Realname  string
	SaslUser  sql.NullString
	SaslPass  sql.NullString
	SortOrder int64
}

func (q *Queries) ListNetworksWithSASL(ctx context.Context) ([]ListNetworksWithSASLRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetworksWithSASL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetworksWithSASLRow{}
	for rows.Next() {
		var i ListNetworksWithSASLRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Host,
			&i.Port,
			&i.Tls,
			&i.Nick,
			&i.Realname,
			&i.SaslUser,
			&i.SaslPass,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNetworkDisabled = `-- name: SetNetworkDisabled :execrows
UPDATE networks SET disabled=? WHERE id=?
`

type SetNetworkDisabledParams struct {
	Disabled int64
	ID       []byte
}

func (q *Queries) SetNetworkDisabled(ctx context.Context, arg SetNetworkDisabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setNetworkDisabled, arg.Disabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setNetworkSortOrder = `-- name: SetNetworkSortOrder :exec
UPDATE networks SET sort_order = ? WHERE id = ?
`

type SetNetworkSortOrderParams struct {
	SortOrder int64
	ID        []byte
}

func (q *Queries) SetNetworkSortOrder(ctx context.Context, arg SetNetworkSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, setNetworkSortOrder, arg.SortOrder, arg.ID)
	return err
}

const updateNetwork = `-- name: UpdateNetwork :execrows
UPDATE networks
SET name = ?, name_ci = ?, host = ?, port = ?, tls = ?, nick = ?, realname = ?, sasl_user = ?, sasl_pass = ?
WHERE id = ?
`

type UpdateNetworkParams struct {
	Name     string
	NameCi   string
	Host     string
	Port     int64
	Tls      int64
	Nick     string
	Realname sql.NullString
	SaslUser sql.NullString
	SaslPass sql.NullString
	ID       []byte
}

func (q *Queries) UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNetwork,
		arg.Name,
		arg.NameCi,
		arg.Host,
		arg.Port,
		arg.Tls,
		arg.Nick,
		arg.Realname,
		arg.SaslUser,
		arg.SaslPass,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertNetwork = `-- name: UpsertNetwork :exec
INSERT INTO networks(id, name, name_ci, kind, host, port, tls, nick, realname, sasl_user, sasl_pass, autoconnect, sort_order, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1,
        (SELECT COALESCE(MAX(sort_order) + 1, 0) FROM networks), ?)
ON CONFLICT(name_ci) DO UPDATE SET
  name=excluded.name, kind=excluded.kind, host=excluded.host, port=excluded.port,
  tls=excluded.tls, nick=excluded.nick, realname=excluded.realname,
  sasl_user=excluded.sasl_user, sasl_pass=excluded.sasl_pass,
  disabled=0
`

type UpsertNetworkParams struct {
	ID        []byte
	Name      string
	NameCi    string
	Kind      string
	Host      string
	Port      int64
	Tls       int64
	Nick      string
	Realname  sql.NullString
	SaslUser  sql.NullString
	SaslPass  sql.NullString
	CreatedAt string
}

func (q *Queries) UpsertNetwork(ctx context.Context, arg UpsertNetworkParams) error {
	_, err := q.db.ExecContext(ctx, upsertNetwork,
		arg.ID,
		arg.Name,
		arg.NameCi,
		arg.Kind,
		arg.Host,
		arg.Port,
		arg.Tls,
		arg.Nick,
		arg.Realname,
		arg.SaslUser,
		arg.SaslPass,
		arg.CreatedAt,
	)
	return err
}
