// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: network_connect_commands.sql

package controldb

import (
	"context"
)

const deleteNetworkConnectCommands = `-- name: DeleteNetworkConnectCommands :exec
DELETE FROM network_connect_commands WHERE network_id = ?
`

func (q *Queries) DeleteNetworkConnectCommands(ctx context.Context, networkID []byte) error {
	_, err := q.db.ExecContext(ctx, deleteNetworkConnectCommands, networkID)
	return err
}

const insertNetworkConnectCommand = `-- name: InsertNetworkConnectCommand :exec
INSERT INTO network_connect_commands(network_id, position, command) VALUES (?, ?, ?)
`

type InsertNetworkConnectCommandParams struct {
	NetworkID []byte
	Position  int64
	Command   string
}

func (q *Queries) InsertNetworkConnectCommand(ctx context.Context, arg InsertNetworkConnectCommandParams) error {
	_, err := q.db.ExecContext(ctx, insertNetworkConnectCommand, arg.NetworkID, arg.Position, arg.Command)
	return err
}

const listNetworkConnectCommands = `-- name: ListNetworkConnectCommands :many
SELECT command FROM network_connect_commands WHERE network_id = ? ORDER BY position
`

func (q *Queries) ListNetworkConnectCommands(ctx context.Context, networkID []byte) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNetworkConnectCommands, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var command string
		if err := rows.Scan(&command); err != nil {
			return nil, err
		}
		items = append(items, command)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
