// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package previewdb

import (
	"database/sql"
)

type UrlPreview struct {
	Url         string
	Kind        string
	Title       sql.NullString
	Description sql.NullString
	ImageUrl    sql.NullString
	SiteName    sql.NullString
	Width       sql.NullInt64
	Height      sql.NullInt64
	Mime        sql.NullString
	FetchedAt   string
	Error       sql.NullString
}
