// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: url_previews.sql

package previewdb

import (
	"context"
	"database/sql"
)

const deleteURLPreviewsBefore = `-- name: DeleteURLPreviewsBefore :execrows
DELETE FROM url_previews WHERE fetched_at < ?
`

func (q *Queries) DeleteURLPreviewsBefore(ctx context.Context, fetchedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteURLPreviewsBefore, fetchedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getURLPreview = `-- name: GetURLPreview :one
SELECT url, kind, COALESCE(title,'') AS title, COALESCE(description,'') AS description,
       COALESCE(image_url,'') AS image_url, COALESCE(site_name,'') AS site_name,
       COALESCE(width,0) AS width, COALESCE(height,0) AS height, COALESCE(mime,'') AS mime,
       fetched_at, COALESCE(error,'') AS error
FROM url_previews WHERE url = ?
`

type GetURLPreviewRow struct {
	Url         string
	Kind        string
	Title       string
	Description string
	ImageUrl    string
	SiteName    string
	Width       int64
	Height      int64
	Mime        string
	FetchedAt   string
	Error       string
}

func (q *Queries) GetURLPreview(ctx context.Context, url string) (GetURLPreviewRow, error) {
	row := q.db.QueryRowContext(ctx, getURLPreview, url)
	var i GetURLPreviewRow
	err := row.Scan(
		&i.Url,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.SiteName,
		&i.Width,
		&i.Height,
		&i.Mime,
		&i.FetchedAt,
		&i.Error,
	)
	return i, err
}

const upsertURLPreview = `-- name: UpsertURLPreview :exec
INSERT INTO url_previews(url, kind, title, description, image_url, site_name,
                         width, height, mime, fetched_at, error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(url) DO UPDATE SET
  kind=excluded.kind,
  title=excluded.title,
  description=excluded.description,
  image_url=excluded.image_url,
  site_name=excluded.site_name,
  width=excluded.width,
  height=excluded.height,
  mime=excluded.mime,
  fetched_at=excluded.fetched_at,
  error=excluded.error
`

type UpsertURLPreviewParams struct {
	Url         string
	Kind        string
	Title       sql.NullString
	Description sql.NullString
	ImageUrl    sql.NullString
	SiteName    sql.NullString
	Width       sql.NullInt64
	Height      sql.NullInt64
	Mime        sql.NullString
	FetchedAt   string
	Error       sql.NullString
}

func (q *Queries) UpsertURLPreview(ctx context.Context, arg UpsertURLPreviewParams) error {
	_, err := q.db.ExecContext(ctx, upsertURLPreview,
		arg.Url,
		arg.Kind,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.SiteName,
		arg.Width,
		arg.Height,
		arg.Mime,
		arg.FetchedAt,
		arg.Error,
	)
	return err
}
