// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package mediadb

import (
	"context"
)

const deleteMedia = `-- name: DeleteMedia :execrows
DELETE FROM media WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMedia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMedia = `-- name: GetMedia :one
SELECT id, kind, mime, source_hash, variants, size, width, height, created_at, updated_at
FROM media WHERE id = ?
`

func (q *Queries) GetMedia(ctx context.Context, id string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Mime,
		&i.SourceHash,
		&i.Variants,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaBySourceHash = `-- name: GetMediaBySourceHash :one
SELECT id, kind, mime, source_hash, variants, size, width, height, created_at, updated_at
FROM media WHERE source_hash = ?
`

func (q *Queries) GetMediaBySourceHash(ctx context.Context, sourceHash string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMediaBySourceHash, sourceHash)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Mime,
		&i.SourceHash,
		&i.Variants,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMedia = `-- name: InsertMedia :exec
INSERT INTO media(id, kind, mime, source_hash, variants, size, width, height, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMediaParams struct {
	ID         string
	Kind       string
	Mime       string
	SourceHash string
	Variants   string
	Size       int64
	Width      int64
	Height     int64
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) InsertMedia(ctx context.Context, arg InsertMediaParams) error {
	_, err := q.db.ExecContext(ctx, insertMedia,
		arg.ID,
		arg.Kind,
		arg.Mime,
		arg.SourceHash,
		arg.Variants,
		arg.Size,
		arg.Width,
		arg.Height,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
