// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mediadb

type Medium struct {
	ID         string
	Kind       string
	Mime       string
	SourceHash string
	Variants   string
	Size       int64
	Width      int64
	Height     int64
	CreatedAt  string
	UpdatedAt  string
}
