// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: buffers.sql

package logdb

import (
	"context"
	"database/sql"
)

const getLogBufferTopicLastSeen = `-- name: GetLogBufferTopicLastSeen :one
SELECT COALESCE(topic,'') AS topic, last_seen_id FROM buffers WHERE name = ?
`

type GetLogBufferTopicLastSeenRow struct {
	Topic      string
	LastSeenID []byte
}

func (q *Queries) GetLogBufferTopicLastSeen(ctx context.Context, name string) (GetLogBufferTopicLastSeenRow, error) {
	row := q.db.QueryRowContext(ctx, getLogBufferTopicLastSeen, name)
	var i GetLogBufferTopicLastSeenRow
	err := row.Scan(&i.Topic, &i.LastSeenID)
	return i, err
}

const insertLogBuffer = `-- name: InsertLogBuffer :exec
INSERT INTO buffers(id, name, kind, created_at) VALUES (?, ?, ?, ?)
`

type InsertLogBufferParams struct {
	ID        []byte
	Name      string
	Kind      string
	CreatedAt string
}

func (q *Queries) InsertLogBuffer(ctx context.Context, arg InsertLogBufferParams) error {
	_, err := q.db.ExecContext(ctx, insertLogBuffer,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}

const listLogBuffers = `-- name: ListLogBuffers :many
SELECT id, name, kind, COALESCE(topic,'') AS topic, last_seen_id, created_at
FROM buffers ORDER BY id
`

type ListLogBuffersRow struct {
	ID         []byte
	Name       string
	Kind       string
	Topic      string
	LastSeenID []byte
	CreatedAt  string
}

func (q *Queries) ListLogBuffers(ctx context.Context) ([]ListLogBuffersRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogBuffers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogBuffersRow{}
	for rows.Next() {
		var i ListLogBuffersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Topic,
			&i.LastSeenID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupLogBuffer = `-- name: LookupLogBuffer :one
SELECT name, kind FROM buffers WHERE id = ?
`

type LookupLogBufferRow struct {
	Name string
	Kind string
}

func (q *Queries) LookupLogBuffer(ctx context.Context, id []byte) (LookupLogBufferRow, error) {
	row := q.db.QueryRowContext(ctx, lookupLogBuffer, id)
	var i LookupLogBufferRow
	err := row.Scan(&i.Name, &i.Kind)
	return i, err
}

const lookupLogBufferByName = `-- name: LookupLogBufferByName :one
SELECT id, COALESCE(topic,'') AS topic, last_seen_id, created_at FROM buffers WHERE name = ?
`

type LookupLogBufferByNameRow struct {
	ID         []byte
	Topic      string
	LastSeenID []byte
	CreatedAt  string
}

func (q *Queries) LookupLogBufferByName(ctx context.Context, name string) (LookupLogBufferByNameRow, error) {
	row := q.db.QueryRowContext(ctx, lookupLogBufferByName, name)
	var i LookupLogBufferByNameRow
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.LastSeenID,
		&i.CreatedAt,
	)
	return i, err
}

const updateLogBufferLastSeen = `-- name: UpdateLogBufferLastSeen :exec
UPDATE buffers SET last_seen_id = ? WHERE name = ?
`

type UpdateLogBufferLastSeenParams struct {
	LastSeenID []byte
	Name       string
}

func (q *Queries) UpdateLogBufferLastSeen(ctx context.Context, arg UpdateLogBufferLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateLogBufferLastSeen, arg.LastSeenID, arg.Name)
	return err
}

const updateLogBufferTopic = `-- name: UpdateLogBufferTopic :exec
UPDATE buffers SET topic = ? WHERE name = ?
`

type UpdateLogBufferTopicParams struct {
	Topic sql.NullString
	Name  string
}

func (q *Queries) UpdateLogBufferTopic(ctx context.Context, arg UpdateLogBufferTopicParams) error {
	_, err := q.db.ExecContext(ctx, updateLogBufferTopic, arg.Topic, arg.Name)
	return err
}
