// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package logdb

import (
	"context"
	"database/sql"
)

const insertLogMessage = `-- name: InsertLogMessage :execrows
INSERT OR IGNORE INTO messages
  (id, buffer_id, msgid, ts, sender, userhost, account, kind, target, content, raw)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLogMessageParams struct {
	ID       []byte
	BufferID []byte
	Msgid    sql.NullString
	Ts       string
	Sender   string
	Userhost string
	Account  sql.NullString
	Kind     string
	Target   sql.NullString
	Content  string
	Raw      string
}

func (q *Queries) InsertLogMessage(ctx context.Context, arg InsertLogMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertLogMessage,
		arg.ID,
		arg.BufferID,
		arg.Msgid,
		arg.Ts,
		arg.Sender,
		arg.Userhost,
		arg.Account,
		arg.Kind,
		arg.Target,
		arg.Content,
		arg.Raw,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const logMessagesBefore = `-- name: LogMessagesBefore :many
SELECT id, buffer_id, COALESCE(msgid,'') AS msgid, ts, sender, COALESCE(userhost,'') AS userhost,
       COALESCE(account,'') AS account, kind, COALESCE(target,'') AS target, content
FROM (
  SELECT rowid, id, buffer_id, msgid, ts, sender, account, kind, target, content, raw, userhost FROM messages WHERE buffer_id = ? AND id < ?
  ORDER BY id DESC LIMIT ?
) ORDER BY id ASC
`

type LogMessagesBeforeParams struct {
	BufferID []byte
	ID       []byte
	Limit    int64
}

type LogMessagesBeforeRow struct {
	ID       []byte
	BufferID []byte
	Msgid    string
	Ts       string
	Sender   string
	Userhost string
	Account  string
	Kind     string
	Target   string
	Content  string
}

func (q *Queries) LogMessagesBefore(ctx context.Context, arg LogMessagesBeforeParams) ([]LogMessagesBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, logMessagesBefore, arg.BufferID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogMessagesBeforeRow{}
	for rows.Next() {
		var i LogMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.BufferID,
			&i.Msgid,
			&i.Ts,
			&i.Sender,
			&i.Userhost,
			&i.Account,
			&i.Kind,
			&i.Target,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentLogMessages = `-- name: RecentLogMessages :many
SELECT id, buffer_id, COALESCE(msgid,'') AS msgid, ts, sender, COALESCE(userhost,'') AS userhost,
       COALESCE(account,'') AS account, kind, COALESCE(target,'') AS target, content
FROM (
  SELECT rowid, id, buffer_id, msgid, ts, sender, account, kind, target, content, raw, userhost FROM messages WHERE buffer_id = ? ORDER BY id DESC LIMIT ?
) ORDER BY id ASC
`

type RecentLogMessagesParams struct {
	BufferID []byte
	Limit    int64
}

type RecentLogMessagesRow struct {
	ID       []byte
	BufferID []byte
	Msgid    string
	Ts       string
	Sender   string
	Userhost string
	Account  string
	Kind     string
	Target   string
	Content  string
}

func (q *Queries) RecentLogMessages(ctx context.Context, arg RecentLogMessagesParams) ([]RecentLogMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, recentLogMessages, arg.BufferID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentLogMessagesRow{}
	for rows.Next() {
		var i RecentLogMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.BufferID,
			&i.Msgid,
			&i.Ts,
			&i.Sender,
			&i.Userhost,
			&i.Account,
			&i.Kind,
			&i.Target,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
