// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package logdb

import (
	"context"
	"database/sql"
)

const deleteLogMessagesForBuffer = `-- name: DeleteLogMessagesForBuffer :exec
DELETE FROM messages WHERE buffer_id = ?
`

// Explicit delete (not FK cascade) so the messages_ad trigger fires and
// keeps the external-content FTS index in sync.
func (q *Queries) DeleteLogMessagesForBuffer(ctx context.Context, bufferID []byte) error {
	_, err := q.db.ExecContext(ctx, deleteLogMessagesForBuffer, bufferID)
	return err
}

const insertLogMessage = `-- name: InsertLogMessage :execrows
INSERT OR IGNORE INTO messages
  (id, buffer_id, msgid, ts, sender, userhost, account, kind, target, content, raw)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLogMessageParams struct {
	ID       []byte
	BufferID []byte
	Msgid    sql.NullString
	Ts       string
	Sender   string
	Userhost string
	Account  sql.NullString
	Kind     string
	Target   sql.NullString
	Content  string
	Raw      string
}

func (q *Queries) InsertLogMessage(ctx context.Context, arg InsertLogMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertLogMessage,
		arg.ID,
		arg.BufferID,
		arg.Msgid,
		arg.Ts,
		arg.Sender,
		arg.Userhost,
		arg.Account,
		arg.Kind,
		arg.Target,
		arg.Content,
		arg.Raw,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const latestLogMessageTS = `-- name: LatestLogMessageTS :one
SELECT CAST(COALESCE(MAX(ts), '') AS TEXT) AS ts FROM messages WHERE buffer_id = ?
`

// Newest stored timestamp for a buffer (uses messages_buffer_ts index).
// Empty string when the buffer has no messages.
func (q *Queries) LatestLogMessageTS(ctx context.Context, bufferID []byte) (string, error) {
	row := q.db.QueryRowContext(ctx, latestLogMessageTS, bufferID)
	var ts string
	err := row.Scan(&ts)
	return ts, err
}

const logMessageInBuffer = `-- name: LogMessageInBuffer :one
SELECT EXISTS(SELECT 1 FROM messages WHERE buffer_id = ? AND id = ?)
`

type LogMessageInBufferParams struct {
	BufferID []byte
	ID       []byte
}

func (q *Queries) LogMessageInBuffer(ctx context.Context, arg LogMessageInBufferParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, logMessageInBuffer, arg.BufferID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const logMessagesBefore = `-- name: LogMessagesBefore :many
SELECT id, buffer_id, COALESCE(msgid,'') AS msgid, ts, sender, COALESCE(userhost,'') AS userhost,
       COALESCE(account,'') AS account, kind, COALESCE(target,'') AS target, content
FROM (
  SELECT rowid, id, buffer_id, msgid, ts, sender, account, kind, target, content, raw, userhost FROM messages WHERE buffer_id = ? AND id < ?
  ORDER BY id DESC LIMIT ?
) ORDER BY id ASC
`

type LogMessagesBeforeParams struct {
	BufferID []byte
	ID       []byte
	Limit    int64
}

type LogMessagesBeforeRow struct {
	ID       []byte
	BufferID []byte
	Msgid    string
	Ts       string
	Sender   string
	Userhost string
	Account  string
	Kind     string
	Target   string
	Content  string
}

func (q *Queries) LogMessagesBefore(ctx context.Context, arg LogMessagesBeforeParams) ([]LogMessagesBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, logMessagesBefore, arg.BufferID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogMessagesBeforeRow{}
	for rows.Next() {
		var i LogMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.BufferID,
			&i.Msgid,
			&i.Ts,
			&i.Sender,
			&i.Userhost,
			&i.Account,
			&i.Kind,
			&i.Target,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentLogMessages = `-- name: RecentLogMessages :many
SELECT id, buffer_id, COALESCE(msgid,'') AS msgid, ts, sender, COALESCE(userhost,'') AS userhost,
       COALESCE(account,'') AS account, kind, COALESCE(target,'') AS target, content
FROM (
  SELECT rowid, id, buffer_id, msgid, ts, sender, account, kind, target, content, raw, userhost FROM messages WHERE buffer_id = ? ORDER BY id DESC LIMIT ?
) ORDER BY id ASC
`

type RecentLogMessagesParams struct {
	BufferID []byte
	Limit    int64
}

type RecentLogMessagesRow struct {
	ID       []byte
	BufferID []byte
	Msgid    string
	Ts       string
	Sender   string
	Userhost string
	Account  string
	Kind     string
	Target   string
	Content  string
}

func (q *Queries) RecentLogMessages(ctx context.Context, arg RecentLogMessagesParams) ([]RecentLogMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, recentLogMessages, arg.BufferID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentLogMessagesRow{}
	for rows.Next() {
		var i RecentLogMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.BufferID,
			&i.Msgid,
			&i.Ts,
			&i.Sender,
			&i.Userhost,
			&i.Account,
			&i.Kind,
			&i.Target,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
