// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: previews.sql

package logdb

import (
	"context"
)

const insertMessagePreviewLink = `-- name: InsertMessagePreviewLink :exec
INSERT OR IGNORE INTO message_previews(message_id, url, position)
VALUES (?, ?, ?)
`

type InsertMessagePreviewLinkParams struct {
	MessageID []byte
	Url       string
	Position  int64
}

func (q *Queries) InsertMessagePreviewLink(ctx context.Context, arg InsertMessagePreviewLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertMessagePreviewLink, arg.MessageID, arg.Url, arg.Position)
	return err
}
